ENV : TEST

TEST:
  database : DATACLOUD_TEST
  user : vpolu
  password : k!ndRock64
  warehouse : DATACLOUD_COMPUTE_WH
STAGE:
  database : DATACLOUD_STAGE
  user : SAETLDEV
  password : KUZKtGuyw7vEmg7
  warehouse : DATACLOUD_STAGE_WH


PROD:
  database : database
  user : user
  password : password


SENDER:
  email : vpolu@epostglobalshipping.com
  password : tfizbwqzvxvhvwaf
  # app password #tfiz bwqz vxvh vwaf
  #password : k!ndRock64

RECEIVERS:
  - vpolu@epostglobalshipping.com
  #- rkarnati@epostglobalshipping.com

#LOG_PATH : E:\3rd_Party_Scheduler\WebScraping\logs

LOG_PATH : .\logs

OFFSET :
  AUSTRIA :
    LAX :
      HOUR : 7 
      MIN  : 0
    ORD:
      HOUR : 7
      MIN  : 0
    EWR :
      HOUR : 7 
      MIN  : 0
  ITALY :
    LAX :
      HOUR : 6 
      MIN  : 0
    ORD:
      HOUR : 6 
      MIN  : 0
    EWR :
      HOUR : 7
      MIN  : 0
  SWITZERLAND :
    LAX :
      HOUR : 7 
      MIN  : 0
    ORD:
      HOUR : 7 
      MIN  : 0
    EWR :
      HOUR : 6 
      MIN  : 0
    MIA :
      HOUR : 6
      MIN  : 0
     
  
#YAML CONFIG
#env name
#snowflake connection details
#mail details
#log path
