INSERT INTO DATACLOUD_TEST.REFERENCE.WEB_SCRAPING_CONFIG_TABLE (REGION,COUNTRY_NAME,COUNTRY_CODE,COUNTRY_CODE_3_DIGIT,POSTAL_SYSTEM_NAME,POSTAL_SYSTEM_URL,SCRAPING_URL,LANGUAGE,CAPTCHA_IND,SELECT_SQL,MIN_SELECTED_DAYS,MAX_SELECTED_DAYS,OUTPUT_PATH,IS_ACTIVE)
VALUES('LATIN AMERICA','CHILE','CL','CHL','CHILE POST','https://posttrack.com/en/parcel-tracking','https://posttrack.com/en/parcel-tracking?tracking_numbers[]=#TRACKING_NUM#','ENGLISH','NO','SELECT TRACKINGNO,FACILITY_CODE FROM (SELECT P.TRACKINGNO,F.FACILITY_CODE,MAX(E.EVENT_DATETIME) AS MAX_EVENT_DATETIME
FROM (SELECT * FROM DATACLOUD.EDW.PARCEL WHERE DELIVERED_DATE IS NULL AND DATE_PROCESSED BETWEEN DATEADD(DAY,#MAX_SELECTED_DAYS#,CURRENT_TIMESTAMP) AND DATEADD(DAY,#MIN_SELECTED_DAYS#,CURRENT_TIMESTAMP)) P
INNER JOIN DATACLOUD.EDW.VENDOR V ON P.VENDOR_ID=V.VENDOR_ID AND TRIM(UPPER(V.VENDOR_NAME)) LIKE ''%USPS%''
INNER JOIN DATACLOUD.EDW.COUNTRY C ON P.COUNTRY_ID=C.COUNTRY_ID  AND TRIM(UPPER(C.COUNTRY_NAME))= ''#COUNTRY_NAME#''
INNER JOIN DATACLOUD.EDW.EVENT E ON P.PARCEL_ID=E.PARCEL_ID
INNER JOIN DATACLOUD.EDW.FACILITY F ON P.FACILITY_ID=F.FACILITY_ID
GROUP BY P.TRACKINGNO,F.FACILITY_CODE
) WHERE MAX_EVENT_DATETIME BETWEEN DATEADD(DAY,#MAX_SELECTED_DAYS#,CURRENT_TIMESTAMP) AND DATEADD(DAY,#MIN_SELECTED_DAYS#,CURRENT_TIMESTAMP);','-7','-30','\\\\sauw1slprdsftp.file.core.windows.net\\cornerstonesftp\\FTPData\\XPO\\EPG\\Stage\\Tracking\\Vendor\\CommonVendor\\sourcepath\\','YES');

INSERT INTO DATACLOUD_TEST.REFERENCE.WEB_SCRAPING_CONFIG_TABLE (REGION,COUNTRY_NAME,COUNTRY_CODE,COUNTRY_CODE_3_DIGIT,POSTAL_SYSTEM_NAME,POSTAL_SYSTEM_URL,SCRAPING_URL,LANGUAGE,CAPTCHA_IND,SELECT_SQL,MIN_SELECTED_DAYS,MAX_SELECTED_DAYS,OUTPUT_PATH,IS_ACTIVE)
VALUES('LATIN AMERICA','MEXICO','MX','MEX','MEXIC0 POST','https://www.correosdemexico.gob.mx/SSLServicios/SeguimientoEnvio/Seguimiento.aspx','https://www.correosdemexico.gob.mx/SSLServicios/SeguimientoEnvio/Seguimiento.aspx','SPANISH','NO','SELECT TRACKINGNO,FACILITY_CODE FROM (SELECT P.TRACKINGNO,F.FACILITY_CODE,MAX(E.EVENT_DATETIME) AS MAX_EVENT_DATETIME
FROM (SELECT * FROM DATACLOUD.EDW.PARCEL WHERE DELIVERED_DATE IS NULL AND DATE_PROCESSED BETWEEN DATEADD(DAY,#MAX_SELECTED_DAYS#,CURRENT_TIMESTAMP) AND DATEADD(DAY,#MIN_SELECTED_DAYS#,CURRENT_TIMESTAMP)) P
INNER JOIN DATACLOUD.EDW.VENDOR V ON P.VENDOR_ID=V.VENDOR_ID AND TRIM(UPPER(V.VENDOR_NAME)) LIKE ''%USPS%''
INNER JOIN DATACLOUD.EDW.COUNTRY C ON P.COUNTRY_ID=C.COUNTRY_ID  AND TRIM(UPPER(C.COUNTRY_NAME))= ''#COUNTRY_NAME#''
INNER JOIN DATACLOUD.EDW.EVENT E ON P.PARCEL_ID=E.PARCEL_ID
INNER JOIN DATACLOUD.EDW.FACILITY F ON P.FACILITY_ID=F.FACILITY_ID
GROUP BY P.TRACKINGNO,F.FACILITY_CODE
) WHERE MAX_EVENT_DATETIME BETWEEN DATEADD(DAY,#MAX_SELECTED_DAYS#,CURRENT_TIMESTAMP) AND DATEADD(DAY,#MIN_SELECTED_DAYS#,CURRENT_TIMESTAMP);','-7','-30','\\\\sauw1slprdsftp.file.core.windows.net\\cornerstonesftp\\FTPData\\XPO\\EPG\\Stage\\Tracking\\Vendor\\CommonVendor\\sourcepath\\','YES');
